aws:
        endpoint_url:
        region: us-east-1
        url_expires: 30
        access_key_id: 
        secret_access_key: 
        default_bucket: 

email:
        smtp_server: 
        from: 
        cc_emails: 
        reply_to: 
        
